### ISSUE TITLE
No support while there is Chinese in hosts file

### ISSUE THREAD

**Issue by ZhangBo1191** [jonhadfield/python-hosts#26]
If there is any comments written in Chinese, the module will throw an error.
> Traceback (most recent call last):
  File "D:\456\akamTester\akamTester.py", line 113, in <module>
    fastHosts = Hosts()
  File "%AppData%\Local\Programs\Python\Python37\lib\site-packages\python_hosts\hosts.py", line 144, in __init__
    self.populate_entries()
  File "%AppData%\Local\Programs\Python\Python37\lib\site-packages\python_hosts\hosts.py", line 433, in populate_entries
    hosts_entries = [line for line in hosts_file]
  File "%AppData%\Local\Programs\Python\Python37\lib\site-packages\python_hosts\hosts.py", line 433, in <listcomp>
    hosts_entries = [line for line in hosts_file]
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence

**Comment by ZhangBo1191** [comment]
See https://github.com/jonhadfield/python-hosts/pull/27 BUT it has lost Python 2.x Support now
